name: Tests

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        pixi-environment: [ py310, py314 ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0
      with:
        manifest-path: pyproject.toml

    - name: Run Tests
      run: pixi run --environment ${{ matrix.pixi-environment }} test
