name: Tests

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        pixi-environment: [ py310, py314 ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11  # v0.9.6
      with:
        manifest-path: pyproject.toml

    - name: Run Tests
      run: pixi run --environment ${{ matrix.pixi-environment }} test
